### ISSUE TITLE
Demo offline

### ISSUE THREAD

**Issue by BrycensRanch** [crazy-man22/netflix-clone-react-typescript#2]
Hi, I really liked the preview of your project, however, the live demo is offline. Vercel is reporting a 404: NOT_FOUND. 

EDIT: You forgot to the demo link in the README.md from the one you posted in Discord

**Comment by jason-liu22** [comment]
Thanks for your feedback.
I checked it and fixed it.
Please try it again.
https://netflix-clone-react-typescript.vercel.app

**Comment by BrycensRanch** [comment]
Many thanks! The site looks great, besides the background videos being low quality. However, I feel this is a issue with YouTube itself. Great job implementing actual trailers!
